//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Atendimentoes = new HashSet<Atendimento>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string NomeMae { get; set; }
        public Nullable<System.DateTime> Nascimento { get; set; }
        public Nullable<int> Sexo { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public System.DateTime DataEdicao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimento> Atendimentoes { get; set; }
    }
}
