//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemploMaterializacao.ServicoExposto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PacienteTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PacienteTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeMaeField;
        
        private System.Nullable<System.DateTime> NascimentoField;
        
        private ExemploMaterializacao.ServicoExposto.SexoEnum SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomeMae {
            get {
                return this.NomeMaeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeMaeField, value) != true)) {
                    this.NomeMaeField = value;
                    this.RaisePropertyChanged("NomeMae");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> Nascimento {
            get {
                return this.NascimentoField;
            }
            set {
                if ((this.NascimentoField.Equals(value) != true)) {
                    this.NascimentoField = value;
                    this.RaisePropertyChanged("Nascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public ExemploMaterializacao.ServicoExposto.SexoEnum Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SexoEnum", Namespace="http://tempuri.org/")]
    public enum SexoEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Masculino = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Feminino = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NaoInformado = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoExposto.ServicoSoap")]
    public interface ServicoSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento GetMeusPacientesResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMeusPacientes", ReplyAction="*")]
        ExemploMaterializacao.ServicoExposto.GetMeusPacientesResponse GetMeusPacientes(ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMeusPacientes", ReplyAction="*")]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.GetMeusPacientesResponse> GetMeusPacientesAsync(ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMeusPacientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMeusPacientes", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequestBody Body;
        
        public GetMeusPacientesRequest() {
        }
        
        public GetMeusPacientesRequest(ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMeusPacientesRequestBody {
        
        public GetMeusPacientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMeusPacientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMeusPacientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExemploMaterializacao.ServicoExposto.GetMeusPacientesResponseBody Body;
        
        public GetMeusPacientesResponse() {
        }
        
        public GetMeusPacientesResponse(ExemploMaterializacao.ServicoExposto.GetMeusPacientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMeusPacientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExemploMaterializacao.ServicoExposto.PacienteTO[] GetMeusPacientesResult;
        
        public GetMeusPacientesResponseBody() {
        }
        
        public GetMeusPacientesResponseBody(ExemploMaterializacao.ServicoExposto.PacienteTO[] GetMeusPacientesResult) {
            this.GetMeusPacientesResult = GetMeusPacientesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicoSoapChannel : ExemploMaterializacao.ServicoExposto.ServicoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoSoapClient : System.ServiceModel.ClientBase<ExemploMaterializacao.ServicoExposto.ServicoSoap>, ExemploMaterializacao.ServicoExposto.ServicoSoap {
        
        public ServicoSoapClient() {
        }
        
        public ServicoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExemploMaterializacao.ServicoExposto.GetMeusPacientesResponse ExemploMaterializacao.ServicoExposto.ServicoSoap.GetMeusPacientes(ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequest request) {
            return base.Channel.GetMeusPacientes(request);
        }
        
        public ExemploMaterializacao.ServicoExposto.PacienteTO[] GetMeusPacientes() {
            ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequest inValue = new ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequestBody();
            ExemploMaterializacao.ServicoExposto.GetMeusPacientesResponse retVal = ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).GetMeusPacientes(inValue);
            return retVal.Body.GetMeusPacientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.GetMeusPacientesResponse> ExemploMaterializacao.ServicoExposto.ServicoSoap.GetMeusPacientesAsync(ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequest request) {
            return base.Channel.GetMeusPacientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExemploMaterializacao.ServicoExposto.GetMeusPacientesResponse> GetMeusPacientesAsync() {
            ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequest inValue = new ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequest();
            inValue.Body = new ExemploMaterializacao.ServicoExposto.GetMeusPacientesRequestBody();
            return ((ExemploMaterializacao.ServicoExposto.ServicoSoap)(this)).GetMeusPacientesAsync(inValue);
        }
    }
}
